In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv('train-data.csv')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [14]:
df.isna().sum()

Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  42
New_Price            5195
Price                   0
dtype: int64

In [15]:
df.isna().mean()*100

Unnamed: 0            0.000000
Name                  0.000000
Location              0.000000
Year                  0.000000
Kilometers_Driven     0.000000
Fuel_Type             0.000000
Transmission          0.000000
Owner_Type            0.000000
Mileage               0.033228
Engine                0.598106
Power                 0.598106
Seats                 0.697790
New_Price            86.310018
Price                 0.000000
dtype: float64

In [16]:
df.drop(columns=['New_Price','Unnamed: 0'],inplace=True)

In [17]:
df.ffill(inplace=True)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,2.50

In [18]:
df.isna().sum()

Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   str
 1   Location           6019 non-null   str
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   str
 5   Transmission       6019 non-null   str
 6   Owner_Type         6019 non-null   str
 7   Mileage            6019 non-null   str
 8   Engine             6019 non-null   str
 9   Power              6019 non-null   str
 10  Seats              6019 non-null   float64
 11  Price              6019 non-null   float64
dtypes: float64(2), int64(2), str(8)
memory usage: 1006.7 KB

In [20]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse_output=False,handle_unknown='ignore')
data = ohe.fit_transform(df[['Location']])
df1 = pd.DataFrame(data,columns=ohe.get_feature_names_out())

In [21]:
ohe1=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
data1=ohe1.fit_transform(df[['Fuel_Type']])
df2=pd.DataFrame(data1,columns=ohe1.get_feature_names_out())

In [22]:
ohe2=OneHotEncoder(sparse_output=False,handle_unknown='ignore')
data2=ohe2.fit_transform(df[['Transmission']])
df3=pd.DataFrame(data2,columns=ohe2.get_feature_names_out())

In [23]:
df=pd.concat([df,df1,df2,df3],axis=1)

In [24]:
df.drop(['Fuel_Type','Transmission','Location'],axis=1,inplace=True)

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   str
 4   Mileage                 6019 non-null   str
 5   Engine                  6019 non-null   str
 6   Power                   6019 non-null   str
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(20), int64(2), str(5)
memory usage: 1.6 MB

In [26]:
df['Owner_Type'].unique()

<ArrowStringArray>
['First', 'Second', 'Fourth & Above', 'Third']
Length: 4, dtype: str

In [27]:
df['Owner_Type']=df['Owner_Type'].replace({'First':0, 'Second':1, 'Fourth & Above':3, 'Third':2})
df['Owner_Type']=df['Owner_Type'].astype(int)

In [28]:
df['Engine'] = df['Engine'].replace({'CC' :''},regex=True)
df['Engine'] = df['Engine'].astype(int)

In [29]:
for i in df['Power'].unique():
    if not i.endswith('bhp'):
      print(i)

In [30]:
df['Power'] = df['Power'].replace({'bhp' :''},regex=True)

In [31]:
df['Power']=df['Power'].str.strip()

In [32]:
import re
for i in df['Power'].unique():
    if not re.match(r'^[0-9,]+$',i):
        print(i)

58.16
126.2
88.7
88.76
140.8
55.2
63.1
171.5
103.6
103.25
116.3
187.7
175.56
98.6
83.8
167.62
88.5
177.01
67.1
108.45
138.1
179.5
103.5
254.8
73.9
46.3
37.5
82.9
149.92
138.03
112.2
163.7
174.33
103.2
53.3
78.9
147.6
147.8
108.5
86.8
187.74
null
86.7
73.94
117.3
168.5
89.84
82.85
241.4
270.9
126.32
100.6
75.94
107.3
37.48
91.1
85.80
362.07
121.3
81.80
76.8
103.52
362.9
67.06
120.7
81.86
88.73
57.6
157.75
102.5
201.1
83.1
68.05
88.50
81.83
64.1
177.5
246.7
177.46
67.04
189.08
53.5
194.3
254.79
66.1
123.24
47.3
88.8
201.15
93.7
177.6
141.1
83.14
67.05
87.2
246.74
98.79
62.1
174.3
335.2
191.34
108.49
138.02
187.4
103.3
164.7
79.4
198.5
73.8
181.43
85.8
207.8
108.4
82.5
364.9
107.2
113.98
126.3
237.4
99.6
66.7
98.59
92.7
147.51
197.2
167.6
110.4
73.97
147.9
116.6
34.2
108.62
118.3
38.4
241.38
153.86
163.5
226.6
84.8
53.64
158.2
69.01
181.03
58.2
104.68
126.24
73.75
130.2
57.5
97.7
121.4
98.96
174.5
121.36
91.72
65.3
88.2
35.5
86.79
157.7
40.3
91.7
114.4
158.8
157.8
123.7
56.3
270.88
167.7
148.31
80.46
138.08
74.9
91.2
102.57
97.6
102.53
112.4
73.74
108.495
116.9
70.02
261.49
105.5
168.7
55.23
94.68
152.88
163.2
203.2
271.23
63.12
85.7
308.43
118.6
199.3
83.83
262.6
58.33
86.76
76.9
174.57
301.73
68.1
394.3
80.9
147.5
120.33
82.4
231.1
335.3
198.25
224.34
71.01
271.72
135.1
64.08
261.5
123.37
175.67
110.5
178.4
193.1
48.21
89.75
387.3
130.3
281.61
52.8
139.01
98.82
139.07
83.11
74.93
74.96
116.4
161.6
488.1
181.04

In [33]:
df['Power'] =  df['Power'].replace({'null':0})
df['Power'] = df['Power'].astype(float)

In [34]:
for i in df['Mileage'].unique():
    if not i.endswith('km/kg') and not i.endswith('kmpl'):
      print(i)

In [35]:
def conv_Mileage(row):
    row = row.lower().strip()
    if row.endswith('km/kg'):
        num = row.replace('km/kg','')
        return float(num)*1.4
    elif row.endswith('kmpl'):
         num = row.replace('kmpl','')
         return float(num)
        
df['Mileage'] = df['Mileage'].apply(conv_Mileage)

In [36]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   str
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   float64
 5   Engine                  6019 non-null   int64
 6   Power                   6019 non-null   float64
 7   Seats                   6019 non-null   float64
 8   Price                   6019 non-null   float64
 9   Location_Ahmedabad      6019 non-null   float64
 10  Location_Bangalore      6019 non-null   float64
 11  Location_Chennai        6019 non-null   float64
 12  Location_Coimbatore     6019 non-null   float64
 13  Location_Delhi          6019 non-null   float64
 14  Location_Hyderabad      6019 non-null   float64
 15  Location_Jaipur         6019 non-null   float64
 16  Location_Kochi          6019 non-null   float64
 17  Location_Kolkata        6019 non-null   float64
 18  Location_Mumbai         6019 non-null   float64
 19  Location_Pune           6019 non-null   float64
 20  Fuel_Type_CNG           6019 non-null   float64
 21  Fuel_Type_Diesel        6019 non-null   float64
 22  Fuel_Type_Electric      6019 non-null   float64
 23  Fuel_Type_LPG           6019 non-null   float64
 24  Fuel_Type_Petrol        6019 non-null   float64
 25  Transmission_Automatic  6019 non-null   float64
 26  Transmission_Manual     6019 non-null   float64
dtypes: float64(22), int64(4), str(1)
memory usage: 1.4 MB

In [37]:
df['Power']=df['Power'].replace({0:np.nan})

In [38]:
df.isna().sum()

Name                        0
Year                        0
Kilometers_Driven           0
Owner_Type                  0
Mileage                     0
Engine                      0
Power                     108
Seats                       0
Price                       0
Location_Ahmedabad          0
Location_Bangalore          0
Location_Chennai            0
Location_Coimbatore         0
Location_Delhi              0
Location_Hyderabad          0
Location_Jaipur             0
Location_Kochi              0
Location_Kolkata            0
Location_Mumbai             0
Location_Pune               0
Fuel_Type_CNG               0
Fuel_Type_Diesel            0
Fuel_Type_Electric          0
Fuel_Type_LPG               0
Fuel_Type_Petrol            0
Transmission_Automatic      0
Transmission_Manual         0
dtype: int64

In [39]:
df.ffill(inplace=True)

,Name,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Location_Ahmedabad,...,Location_Kolkata,Location_Mumbai,Location_Pune,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Electric,Fuel_Type_LPG,Fuel_Type_Petrol,Transmission_Automatic,Transmission_Manual
0,Maruti Wagon R LXI CNG,2010,72000,0,37.24,998,58.16,5.0,1.75,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1,Hyundai Creta 1.6 CRDi SX Option,2015,41000,0,19.67,1582,126.20,5.0,12.50,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,Honda Jazz V,2011,46000,0,18.20,1199,88.70,5.0,4.50,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
3,Maruti Ertiga VDI,2012,87000,0,20.77,1248,88.76,7.0,6.00,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,Audi A4 New 2.0 TDI Multitronic,2013,40670,1,15.20,1968,140.80,5.0,17.74,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,2014,27365,0,28.40,1248,74.00,5.0,4.75,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6015,Hyundai Xcent 1.1 CRDi S,2015,100000,0,24.40,1120,71.00,5.0,4.00,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6016,Mahindra Xylo D4 BSIV,2012,55000,1,14.00,2498,112.00,8.0,2.90,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
6017,Maruti Wagon R VXI,2013,46000,0,18.90,998,67.10,5.0,2.65,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
6018,Chevrolet Beat Diesel,2011,47000,0,25.44,936,57.60,5.0,2.50,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [40]:
df.isna().sum()

Name                      0
Year                      0
Kilometers_Driven         0
Owner_Type                0
Mileage                   0
Engine                    0
Power                     0
Seats                     0
Price                     0
Location_Ahmedabad        0
Location_Bangalore        0
Location_Chennai          0
Location_Coimbatore       0
Location_Delhi            0
Location_Hyderabad        0
Location_Jaipur           0
Location_Kochi            0
Location_Kolkata          0
Location_Mumbai           0
Location_Pune             0
Fuel_Type_CNG             0
Fuel_Type_Diesel          0
Fuel_Type_Electric        0
Fuel_Type_LPG             0
Fuel_Type_Petrol          0
Transmission_Automatic    0
Transmission_Manual       0
dtype: int64

In [41]:
x=df.drop(['Price'],axis=1)
y=df['Price']

In [42]:
pip install category_encoders

Requirement already satisfied: category_encoders in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (2.4.2)
Requirement already satisfied: pandas>=1.0.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (3.0.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.0.2)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (1.17.0)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from category_encoders) (0.14.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas>=1.0.5->category_encoders) (2025.3)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\hp\appdata\roaming\python\python311\site-packages (from statsmodels>=0.9.0->category_encoders) (26.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [43]:
import category_encoders as ce
te = ce.TargetEncoder(cols=['Name'])
df = te.fit_transform(x,y)

In [44]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Name                    6019 non-null   float64
 1   Year                    6019 non-null   int64
 2   Kilometers_Driven       6019 non-null   int64
 3   Owner_Type              6019 non-null   int64
 4   Mileage                 6019 non-null   float64
 5   Engine                  6019 non-null   int64
 6   Power                   6019 non-null   float64
 7   Seats                   6019 non-null   float64
 8   Location_Ahmedabad      6019 non-null   float64
 9   Location_Bangalore      6019 non-null   float64
 10  Location_Chennai        6019 non-null   float64
 11  Location_Coimbatore     6019 non-null   float64
 12  Location_Delhi          6019 non-null   float64
 13  Location_Hyderabad      6019 non-null   float64
 14  Location_Jaipur         6019 non-null   float64
 15  Location_Kochi          6019 non-null   float64
 16  Location_Kolkata        6019 non-null   float64
 17  Location_Mumbai         6019 non-null   float64
 18  Location_Pune           6019 non-null   float64
 19  Fuel_Type_CNG           6019 non-null   float64
 20  Fuel_Type_Diesel        6019 non-null   float64
 21  Fuel_Type_Electric      6019 non-null   float64
 22  Fuel_Type_LPG           6019 non-null   float64
 23  Fuel_Type_Petrol        6019 non-null   float64
 24  Transmission_Automatic  6019 non-null   float64
 25  Transmission_Manual     6019 non-null   float64
dtypes: float64(22), int64(4)
memory usage: 1.2 MB

In [45]:
x.shape

(6019, 26)

In [46]:
y

0        1.75
1       12.50
2        4.50
3        6.00
4       17.74
        ...
6014     4.75
6015     4.00
6016     2.90
6017     2.65
6018     2.50
Name: Price, Length: 6019, dtype: float64

In [47]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(df,y,test_size=0.25,random_state=42)

In [48]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()
model.fit(xtrain,ytrain)

RandomForestRegressor()

In [49]:
ypred=model.predict(xtest)

In [50]:
from sklearn.metrics import r2_score
print("r2 score :",r2_score(ytest,ypred))

r2 score : 0.9478058487916078

In [51]:
import pickle

In [52]:
pickle.dump(model,open('model.sav','wb'))

In [ ]:
pickle.dump(ohe,open('ohe_loc.sav','wb'))

In [54]:
pickle.dump(ohe1,open('ohe1_fuel.sav','wb'))

In [ ]:
pickle.dump(ohe2,open('ohe2_Transmission.sav','wb'))

In [56]:
pickle.dump(te,open('te_name','wb'))

In [57]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (1.56.0)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.1.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.0.6)
Requirement already satisfied: click<9,>=7.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (8.3.3)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.1.47)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.4.2)
Requirement already satisfied: packaging>=20 in c:\users\hp\appdata\roaming\python\python311\site-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (3.0.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (12.1.1)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.9.2)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (7.34.1)
Requirement already satisfied: pyarrow>=7.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (24.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (2.33.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\hp\appdata\roaming\python\python311\site-packages (from streamlit) (6.5.4)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\hp\appdata\roaming\python\python311\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: jinja2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.20.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (3.13)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.4.22)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip